apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "3-oba"
  description: "3-oba"
  annotations:
    github.com/project-slug: Paridhi-Mohindra/3-oba
    backstage.io/techdocs-ref: url:https://github.com/Paridhi-Mohindra/3-oba
spec:
  type: service
  lifecycle: experimental
  owner: "3-oba"